# Generated by Django 5.2.9 on 2026-08-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_specialistrating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistrating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
