# Generated by Django 6.0 on 2026-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_alter_session_id_alter_sessionnote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='proposal_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='proposed_by',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'الأخصائي'), ('PATIENT', 'المريض')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='proposed_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
