# Generated by Django 5.2.9 on 2026-08-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_session_proposal_count_session_proposed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
